name: breakly
description: "Aplicación Flutter para sesiones de trabajo sin interrupciones con sincronización remota."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.9.2
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  flutter_launcher_icons: ^0.14.4
  
  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Code generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Supabase
  supabase_flutter: ^2.5.6
  uuid: ^4.4.0
  
  # Encryption
  crypto: ^3.0.3
  
  # Environment variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  riverpod_generator: ^2.4.3
  json_serializable: ^6.8.0
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/black_hole.mp4
    - assets/canyon.avif
    - assets/monk.png
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/monk.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/monk.png"
